#!/bin/bash
scriptname="$0"
translatedir=`dirname $scriptname`
translatepath=`echo ${translatedir}/translate/{convert,tools}`
(
echo "#!/bin/bash"
echo export PYTHONPATH='$PYTHONPATH':"${translatedir}"
for translatesubdir in ${translatepath}
 do
  echo export PATH='$PATH':"${translatesubdir}"
 done
) > $translatedir/setpath

