INSERT INTO "web_language" VALUES(1, 'af', 'Afrikaans', '', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(2, 'ak', 'Akan', '(n > 1)', ''); 
INSERT INTO "web_language" VALUES(3, 'ar', 'Arabic', '6', 'n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n>=3 && n<=10 ? 3 : n>=11 && n<=99 ? 4 : 5', ''); 
INSERT INTO "web_language" VALUES(4, 'az', 'Azerbaijani', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(5, 'be', 'Belarusian', '3', '(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)', ''); 
INSERT INTO "web_language" VALUES(6, 'bg', 'Bulgarian', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(7, 'bn', 'Bengali', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(8, 'bo', 'Tibetan', '1', '0', ''); 
INSERT INTO "web_language" VALUES(9, 'bs', 'Bosnian', '3', '(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)', ''); 
INSERT INTO "web_language" VALUES(10, 'ca', 'Catalan', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(11, 'cs', 'Czech', '3', '(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2', ''); 
INSERT INTO "web_language" VALUES(12, 'cy', 'Welsh', '2', '(n==2) ? 1 : 0', ''); 
INSERT INTO "web_language" VALUES(13, 'da', 'Danish', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(14, 'de', 'German', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(15, 'dz', 'Dzongkha', '1', '0', ''); 
INSERT INTO "web_language" VALUES(16, 'el', 'Greek', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(17, 'en', 'English', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(18, 'en_GB', 'English (British)', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(19, 'en_ZA', 'English (South African)', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(20, 'eo', 'Esperanto', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(21, 'es', 'Spanish', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(22, 'et', 'Estonian', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(23, 'eu', 'Basque', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(24, 'fa', 'Persian', '1', '0', ''); 
INSERT INTO "web_language" VALUES(25, 'fi', 'Finnish', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(26, 'fo', 'Faroese', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(27, 'fr', 'French', '2', '(n > 1)', ''); 
INSERT INTO "web_language" VALUES(28, 'fur', 'Friulian', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(29, 'fy', 'Frisian', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(30, 'ga', 'Irish', '3', 'n==1 ? 0 : n==2 ? 1 : 2', ''); 
INSERT INTO "web_language" VALUES(31, 'gl', 'Galician', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(32, 'gu', 'Gujarati', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(33, 'he', 'Hebrew', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(34, 'hi', 'Hindi', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(35, 'hr', 'Croatian', '3', '(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)', ''); 
INSERT INTO "web_language" VALUES(36, 'hu', 'Hungarian', '1', '0', ''); 
INSERT INTO "web_language" VALUES(37, 'id', 'Indonesian', '1', '0', ''); 
INSERT INTO "web_language" VALUES(38, 'is', 'Icelandic', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(39, 'it', 'Italian', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(40, 'ja', 'Japanese', '1', '0', ''); 
INSERT INTO "web_language" VALUES(41, 'ka', 'Georgian', '1', '0', ''); 
INSERT INTO "web_language" VALUES(42, 'km', 'Khmer', '1', '0', ''); 
INSERT INTO "web_language" VALUES(43, 'ko', 'Korean', '1', '0', ''); 
INSERT INTO "web_language" VALUES(44, 'ku', 'Kurdish', '2', '(n!= 1)', ''); 
INSERT INTO "web_language" VALUES(45, 'lb', 'Letzeburgesch', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(46, 'lt', 'Lithuanian', '3', '(n%10==1 && n%100!=11 ? 0 : n%10>=2 && (n%100<10 || n%100>=20) ? 1 : 2)', ''); 
INSERT INTO "web_language" VALUES(47, 'lv', 'Latvian', '3', '(n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : 2)', ''); 
INSERT INTO "web_language" VALUES(48, 'mn', 'Mongolian', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(49, 'mr', 'Marathi', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(50, 'ms', 'Malay', '1', '0', ''); 
INSERT INTO "web_language" VALUES(51, 'mt', 'Maltese', '4', '(n==1 ? 0 : n==0 || ( n%100>1 && n%100<11) ? 1 : (n%100>10 && n%100<20 ) ? 2 : 3)', ''); 
INSERT INTO "web_language" VALUES(52, 'nah', 'Nahuatl', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(53, 'nb', 'Norwegian Bokmal', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(54, 'ne', 'Nepali', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(55, 'nl', 'Dutch', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(56, 'nn', 'Norwegian Nynorsk', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(57, 'nso', 'Northern Sotho', '2', '(n > 1)', ''); 
INSERT INTO "web_language" VALUES(58, 'or', 'Oriya', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(59, 'pa', 'Punjabi', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(60, 'pl', 'Polish', '3', '(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)', ''); 
INSERT INTO "web_language" VALUES(61, 'pt', 'Portuguese', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(62, 'pt_BR', 'Brazilian Portuguese', '2', '(n > 1)', ''); 
INSERT INTO "web_language" VALUES(63, 'ro', 'Romanian', '3', '(n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < 20)) ? 1 : 2);', ''); 
INSERT INTO "web_language" VALUES(64, 'ru', 'Russian', '3', '(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)', ''); 
INSERT INTO "web_language" VALUES(65, 'sk', 'Slovak', '3', '(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2', ''); 
INSERT INTO "web_language" VALUES(66, 'sl', 'Slovenian', '4', '(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3)', ''); 
INSERT INTO "web_language" VALUES(67, 'sq', 'Albanian', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(68, 'sr', 'Serbian', '3', '(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)', ''); 
INSERT INTO "web_language" VALUES(69, 'sv', 'Swedish', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(70, 'ta', 'Tamil', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(71, 'tk', 'Turkmen', '2', '(n != 1)', ''); 
INSERT INTO "web_language" VALUES(72, 'tr', 'Turkish', '1', '0', ''); 
INSERT INTO "web_language" VALUES(73, 'uk', 'Ukrainian', '3', '(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)', ''); 
INSERT INTO "web_language" VALUES(74, 'vi', 'Vietnamese', '1', '0', ''); 
INSERT INTO "web_language" VALUES(75, 'wa', 'Waloon', '2', '(n > 1)', ''); 
INSERT INTO "web_language" VALUES(76, 'zh_CN', 'Chinese (China)', '1', '0', ''); 
INSERT INTO "web_language" VALUES(77, 'zh_HK', 'Chinese (Hong Kong)', '1', '0', '');
INSERT INTO "web_language" VALUES(78, 'zh_TW', 'Chinese (Taiwan)', '1', '0', ''); 
