# DO NOT EDIT THIS FILE, these are the default settings. Rather 
# edit your settings which are imported at the end.

STORAGE_ROOT_PATH='/var/lib/pootle/storage/'



# import site specific settings
try:
    from Pootle.storage_settings import *
except ImportError:
    print 'No site specific settings found, using defaults.'
