# DO NOT EDIT THIS FILE, these are the default settings. Rather 
# edit your settings which are imported at the end.

# This is the path to root of repository.
STORAGE_ROOT_PATH='/var/lib/pootle/storage/'


# This effects how the directories are mapped to better accomodate 
# distinct needs of projects and translators.
#
# To use layout '/project/language', set to 'provider'.
# To use layout '/language/project', set to 'translator'.
STORAGE_LAYOUT='translator'


# import site specific settings
try:
    from Pootle.storage_settings import *
except ImportError:
    print 'No site specific settings found, using defaults.'
