#!/bin/bash
# this is a script for running repeated tests on different hosts for bugday
timestamp=`date '+%Y%m%d-%H%M'`
bugday=`date '+%Y%m%d'`
hostname=`hostname`
dest=sourceforge:translate/html/bugdays/${bugday}
scriptdir="`dirname "$0"`"
srcdir="`cd "${scriptdir}" ; cd .. ; pwd`"

cd "$srcdir"
mkdir -p testlogs

bugfile=toolkit-bugreport-${timestamp}.html
wget 'http://bugs.wordforge.org:9880/buglist.cgi?query_format=specific&order=relevance+desc&bug_status=__all__&product=Translate+Toolkit' -O testlogs/${bugfile}
scp -p testlogs/${bugfile} ${dest}/$bugfile

bugfile=pootle-bugreport-${timestamp}.html
wget 'http://bugs.wordforge.org:9880/buglist.cgi?query_format=specific&order=relevance+desc&bug_status=__all__&product=Pootle' -O testlogs/${bugfile}
scp -p testlogs/${bugfile} ${dest}/$bugfile

for f in ~/.gaim/logs/irc/*@irc.freenode.net/\#pootle.chat/{2006-03-23,2006-03-22}*
  do
    dorsync "$f" ${dest}/irc-log-`basename "$f"`
  done

