#!/bin/bash
#
# Copyright 2005 Zuza Software Foundation
#
# This file is part of The Translate Toolkit.
#
# The Translate Toolkit is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with translate; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


# mozcvs2po - create po tree from existing locales in l10n directory.
# Launched from the directory where "mozilla" and "l10n" directories are located.
# parameters:
#   * Product: one of "C" -> Common; ·F· -> Firefox, "T", Thunderbird 
#   * Mozilla-CVS: the Mozilla source directory
#   * POT - the output POT directory
#   * Mozilla-l10n: the l10n source directory
#   * Locale: the locale to be converted to PO format
#
# Common
#% C	dom/locales/en-US/	dom/
#% C	netwerk/locales/en-US/	netwerk/
#% C	security/manager/locales/en-US/	security/manager/
#% C	toolkit/locales/en-US/	toolkit/
# Firefox 1.5
#% F	browser/locales/en-US/	browser/
#% F	other-licenses/branding/firefox/locales/en-US	other-licenses/branding/firefox/
#% F	extensions/reporter/locales/en-US/	extensions/reporter/
# Thunderbird 1.5
#% T	editor/ui/locales/en-US/	editor/
#% T	mail/locales/en-US/	mail/
#% T	other-licenses/branding/thunderbird/locales/en-US	other-licenses/branding/thunderbird/

if [ ! $1 ]; then
  echo "Usage: `basename $0` {C|F|T} mozilla-cvs pot [locale-cvs ab-CD]"
  exit 1
fi

requiredproduct=$1
mozillasourcedir=$2
potdir=$3
propdtddir=mozilla.l10n
egrep "^#% " $0 | cut -d" " -f2- | while read product from to
do
  if [ "$requiredproduct" == "$product" ]; then
      mkdir -p $propdtddir/$to
      cp -rp $mozillasourcedir/$from/* $propdtddir/$to
  fi
done

moz2po -P $propdtddir $potdir

if [ $# -ne 5 ]; then
	exit
fi

l10ndir=$4
locale=$5

moz2po -t $propdtddir $l10ndir/$locale $locale
