#!/bin/bash

# Creates a PO Compendium ie a merge of all PO files in a given directory and
# subdirectory.  If conflicts in the merge are found then these are
# combined and marked fuzzy.

if [ $# -lt 2 ]; then
	echo "Usage: `basename $0` output.po directory(s)"
	echo "       The first parameter is the output file, standard output if the output file is '-'."
	echo "       Any number of directories may be specified for input files."
	exit 1
fi

output=$1
shift
directories=$*

# if [ $# -eq 2 ]; then
# 	msgcat -o $2 `find $directory -name "*.po"` 
# else
# 	msgcat `find $directory -name "*.po"`
# fi

touch $output
for dir in $directories
do
	tmp=`mktemp`
	msgcat -o $tmp `find $dir -name "*.po"`
	tmp2=`mktemp`
	cp $output $tmp2
	msgcat -o $output $tmp $tmp2
	rm $tmp $tmp2
done
