#!/bin/bash

# Usage: migrate <lamg-from> <lang-to> <templates>

if [ $# -ne 3 ]; then
	echo "Usage `basename $0` <product-old> <product-new> <product-templates>"
	exit 1
fi

old=$1
new=$2
templates=$3

echo "Migrating files..."
for pot in `cd $templates; find . -name "*.pot"`
do
	filename=`basename $pot .pot`.po
	directory=`dirname $pot`
	mkdir -p $new/$directory
	if [ `find $old -name "$filename" | wc -l` -ge 1 ]; then
		msgcat -o $new/$directory/$filename `find $old -name "$filename" -printf "%p "` && echo Migrated $new/$directory/$filename
	else
		msginit --locale=af_ZA --no-translator -i $templates/$pot -o $new/$directory/$filename
    fi
done

echo "Creating compendium from old files..."
compendium=`mktemp`
msgcat -o $compendium `find $old -name "*.po"`

echo "Updating files using compendium..."
for po in `cd $new ; find . -name "*.po"`
do
	echo -n $new/$po
	msgmerge --compendium=$compendium --update $new/$po $templates/${po}t
done

rm $compendium
