#!/bin/bash
#
# Copyright 2004, 2005 Zuza Software Foundation
#
# This file is part of The Translate Toolkit.
#
# The Translate Toolkit is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# translate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with translate; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


# pomigrate2 - migrates PO files from an old version using new POT files.


function usage() {
	echo "Usage `basename $0` [options] <product-old> <product-new> <product-templates>"
        echo
        echo "Options:"
        echo "   -F|--use-fuzzy-matching - use fuzzy algorithms when merging to attempt to match strings"
        echo "   -C|--use-compendium     - create and use a compendium built from the migrating files"
        echo "   -C|--use-compendium=some-compendium.po"
	echo "                           - use an external compendium during the migration"
        echo "   --no-wrap               - do not wrap long lines"
        echo "   --locale=lang           - set locale for newly born files"
	exit 1
}

option_no_fuzzy_matching="--no-fuzzy-matching"

while true
do
	case $1 in
		-F|--use-fuzzy-matching)
			option_no_fuzzy_matching=""
			shift
			;;
		-C|--use-compendium)
			option_use_compendium="--compendium"
			shift
			;;
		-C=*|--use-compendium=*)
			option_use_own_compendium="$option_use_own_compendium --compendium=`echo $1 | sed 's/\-C=\|--use-compendium=//'`"
			shift
			;;
		--no-wrap)
			option_no_wrap="--no-wrap"
			shift
			;;
		--locale=*)
			option_locale=`echo $1 | sed 's/--locale=//'`
			shift
			;;
		--locale)
			shift
                        if [ $# -lt 1 ]; then
                            usage
                        fi
			option_locale=$1
                        shift
			;;
		-*|--*)
			usage
			;;
		*)
			break
			;;
	esac
done

if [ $# -ne 3 ]; then
	usage
fi

old=$1
new=$2
templates=$3

echo "** Migrating files... **"
pots=`cd $templates; find . -name "*.pot"`
if [ "$pots" == "" ]; then
	echo "No POT templates found in: $templates"
	exit 1
fi
for pot in $pots
do
	filename=`basename $pot .pot`.po
	directory=`dirname $pot`
	mkdir -p $new/$directory
	if [ -f $old/$directory/$filename ]; then
		cp -p $old/$directory/$filename $new/$directory/$filename && echo Copied $new/$directory/$filename
	else
		if [ `find $old -name "$filename" | wc -l` -ge 1 ]; then
			msgcat $option_no_wrap -o $new/$directory/$filename `find $old -name "$filename" -printf "%p "` && echo Migrated $new/$directory/$filename
		else
			msginit $option_no_wrap --locale=$option_locale --no-translator -i $templates/$pot -o $new/$directory/$filename
		fi
	fi
done

if [ "$option_use_compendium" != "" ]; then
	echo "** Creating compendium from old files... **"
	compendium=`mktemp`
	msgcat -o $compendium `find $old -name "*.po"`
	option_use_compendium=" --compendium=$compendium "
fi

echo "** Updating files against templates (optionally with compendium)... **"
for po in `cd $new ; find . -name "*.po" | sort`
do
	echo -n $new/$po
	msgmerge $option_no_fuzzy_matching $option_no_wrap $option_use_compendium $option_use_own_compendium --backup=off --update $new/$po $templates/${po}t
done

if [ "$option_use_compendium" != "" ]; then
	rm $compendium
fi
