#!/bin/bash

# Usage: migrate [options] <lamg-from> <lang-to> <templates>

function usage() {
	echo "Usage `basename $0` [options] <product-old> <product-new> <product-templates>"
        echo
        echo "Options:"
        echo "   -N|--no-fuzzy-matching"
        echo "   --no-wrap  -  do not wrap long lines"
	exit 1
}

while true
do
	case $1 in
		-N|--no-fuzzy-matching)
			option_no_fuzzy_matching = "--no-fuzzy-matching"
			shift
			;;
		--no-wrap)
			option_no_wrap = "--no-wrap"
			shift
			;;
		-*|--*)
			usage
			;;
		*)
			break
			;;
	esac
done
	
if [ $# -ne 3 ]; then
	usage
fi

old=$1
new=$2
templates=$3

echo "** Migrating files... **"
for pot in `cd $templates; find . -name "*.pot"`
do
	filename=`basename $pot .pot`.po
	directory=`dirname $pot`
	mkdir -p $new/$directory
	if [ `find $old -name "$filename" | wc -l` -ge 1 ]; then
		msgcat $option_no_wrap -o $new/$directory/$filename `find $old -name "$filename" -printf "%p "` && echo Migrated $new/$directory/$filename
	else
		msginit $option_no_wrap --locale=af_ZA --no-translator -i $templates/$pot -o $new/$directory/$filename
    fi
done

echo "** Creating compendium from old files... **"
compendium=`mktemp`
msgcat -o $compendium `find $old -name "*.po"`

echo "** Updating files using compendium... **"
for po in `cd $new ; find . -name "*.po" | sort`
do
	echo -n $new/$po
	msgmerge $option_no_fuzzy_matching $option_no_wrap --compendium=$compendium --backup=off --update $new/$po $templates/${po}t
done

rm $compendium
