#!/bin/bash

# poreencode will traverse a PO directory and reencode all files to the
# specified encoding
#
# Usage: poreencode <encoding> <PO directory>

if [ $# -ne 2 ]; then
	echo "Usage: `basename $0` <encoding> <PO directory>"
	echo "   eg: `basename $0` UTF-8 af/"
	exit 1
fi

encoding=$1
po_dir=$2

for po_file in `find $po_dir -name "*.po"`
do
	tmp=`mktemp`
	msgconv -o $tmp $po_file && mv $tmp $po_file
done
