#!/bin/bash

# compendium_split takes any po file but usually a compendium
# and converts it into 3 distinct files named:
#	compendium-translated.po
#	compendium-fuzzy.po
#	compendium-untranslated.po
# and removes the original.
# a simple msgcat can recombine the PO

if [ $# -ne 1 ]; then
	echo "Usage: `basename $0` compendium.po"
	exit 1
fi

compendium=$1

if [ ! -f $compendium ]; then
	echo "Problem with compendium '$compendium'"
	exit 1
fi

dir=`echo $compendium | sed 's/\/[^\/]*$//'`
prefix=$dir/`basename $compendium .po`
translated=${prefix}-translated.po
fuzzy=${prefix}-fuzzy.po
untranslated=${prefix}-untranslated.po

rm -f $translated $fuzzy $untranslated

msgattrib --output-file=$translated --translated --no-fuzzy $compendium
msgattrib --output-file=$fuzzy --only-fuzzy $compendium
msgattrib --output-file=$untranslated --untranslated $compendium

chown .translators $translated $fuzzy $untranslated
chmod g+w $translated $fuzzy $untranslated

rm $compendium
